-- 년, 월, 성별 별로 상품을 구매한 회원수 집계
-- 년, 월, 성별 기준 오름차순
-- 성별 정보 없는 경우 제외
SELECT YEAR(O.SALES_DATE) AS YEAR,
        MONTH(O.SALES_DATE) AS MONTH,
        U.GENDER,
        COUNT(DISTINCT O.USER_ID) AS USERS
FROM ONLINE_SALE O
INNER JOIN USER_INFO U ON O.USER_ID = U.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, U.GENDER
ORDER BY YEAR, MONTH, U.GENDER

# SELECT YEAR(SALES_DATE) AS YEAR, 
# 		MONTH(SALES_DATE) AS MONTH, 
#         GENDER, 
#         COUNT(DISTINCT ONLINE_SALE.USER_ID) AS USERS
# FROM ONLINE_SALE
# INNER JOIN USER_INFO ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
# WHERE GENDER IS NOT NULL
# GROUP BY YEAR, MONTH, GENDER
# ORDER BY YEAR, MONTH, GENDER;
