-- 동물 보호소에 들어온 동물 중 고양이, 개가 각각 몇 마리인지 조회
-- 고양이 먼저 조회
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) as count
FROM ANIMAL_INS
WHERE ANIMAL_TYPE LIKE "Cat" OR ANIMAL_TYPE LIKE "Dog"
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE