-- 입양을 못 간 동물 중 가장 오래 보호소에 있던 동물 3마리의 이름, 보호 시작일
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.DATETIME is NULL
ORDER BY I.DATETIME ASC
LIMIT 3
;